# Generated by Django 4.1.3 on 2023-01-27 17:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shop', '0147_alter_product_fake_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='daily_items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Име на daily item')),
            ],
        ),
        migrations.CreateModel(
            name='daily_row',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Количина')),
                ('price', models.IntegerField(verbose_name='Цена на продукт')),
                ('neto_price', models.IntegerField(verbose_name='Нето вредност')),
                ('stock_price', models.IntegerField(verbose_name='Набавка')),
                ('fixed_cost', models.IntegerField(verbose_name='Фиксен трошок')),
                ('ad_cost', models.IntegerField(verbose_name='Трошок за реклама')),
                ('profit', models.IntegerField(verbose_name='Профит(ЌЕШ)')),
                ('cost_per_purchase', models.IntegerField(verbose_name='Cost per purchase')),
                ('be_roas', models.FloatField(verbose_name='BE ROAS')),
                ('roas', models.FloatField(verbose_name='ROAS')),
                ('roi', models.FloatField(verbose_name='ROI')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Креиран во')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Упдејтиран/Импортиран во')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.daily_items', verbose_name='Дневен ред на информации')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.product', verbose_name='Продукт')),
            ],
        ),
    ]
