# Generated by Django 4.1.3 on 2022-11-15 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
