# Generated by Django 4.1.3 on 2022-11-16 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_order_orderitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='thumnail',
            new_name='thumbnail',
        ),
    ]
