# Generated by Django 4.1.3 on 2022-11-16 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_review_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='Product',
            new_name='product',
        ),
    ]
