# Generated by Django 4.1.3 on 2022-11-16 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_alter_review_product_alter_review_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed'), ('Refunded', 'Refunded'), ('Deleted', 'Deleted')], default='Pending', max_length=50),
        ),
    ]
