# Generated by Django 4.1.3 on 2022-11-17 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_order_shipping_alter_orderitem_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Refunded', 'Refunded'), ('Deleted', 'Deleted')], default='Pending', max_length=50),
        ),
    ]
