# Generated by Django 4.1.3 on 2022-11-17 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_alter_product_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='title_slug',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
