# Generated by Django 4.1.3 on 2022-11-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0033_alter_category_options_alter_dobavuvac_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='items_count',
            field=models.IntegerField(default=1),
        ),
    ]
