# Generated by Django 4.1.3 on 2022-11-17 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0034_cart_items_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='items_count',
        ),
    ]
