# Generated by Django 4.1.3 on 2022-11-18 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0035_remove_cart_items_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('PRIVATE', 'PRIVATE'), ('PUBLISHED', 'PUBLISHED')], default='PRIVATE', max_length=50, verbose_name='СТАТУС'),
        ),
    ]
