# Generated by Django 4.1.3 on 2022-11-19 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0039_productattribute_size_alter_productattribute_price_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='size',
        ),
        migrations.AddField(
            model_name='product',
            name='has_attributes',
            field=models.BooleanField(default=0),
        ),
    ]
