# Generated by Django 4.1.3 on 2022-11-19 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0041_remove_product_has_attributes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes_type',
            field=models.CharField(blank=True, choices=[('COLOR', 'COLOR'), ('SIZE', 'SIZE'), ('OFFER', 'OFFER')], max_length=50),
        ),
    ]
