# Generated by Django 4.1.3 on 2022-11-19 15:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0042_alter_product_attributes_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.size'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
        ),
    ]
