# Generated by Django 4.1.3 on 2022-11-19 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0043_productattribute_size_alter_productattribute_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='color_code',
        ),
    ]
