# Generated by Django 4.1.3 on 2022-11-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0044_remove_size_color_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='color_code',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
