# Generated by Django 4.1.3 on 2022-11-19 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0045_size_color_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='color_code',
        ),
    ]
