# Generated by Django 4.1.3 on 2022-11-19 15:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0048_offer_productattribute_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productattribute',
            old_name='Offer',
            new_name='offer',
        ),
    ]
