# Generated by Django 4.1.3 on 2022-11-22 14:45

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0051_product_desc2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
