# Generated by Django 4.1.3 on 2022-11-23 02:05

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0054_product_thumbnail2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality='80', scale=None, size=[600, 600], upload_to='products/'),
        ),
    ]
