# Generated by Django 4.1.3 on 2022-11-23 02:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0056_remove_product_thumbnail2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content',
        ),
    ]
