# Generated by Django 4.1.3 on 2022-11-23 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0057_remove_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content',
            field=models.TextField(default='hehehehheh', verbose_name='Содржина'),
            preserve_default=False,
        ),
    ]
