# Generated by Django 4.1.3 on 2022-11-23 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0058_review_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='thumbnail_loop',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
