# Generated by Django 4.1.3 on 2022-11-23 02:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0059_review_thumbnail_loop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='thumbnail_loop',
        ),
    ]
