# Generated by Django 4.1.3 on 2022-11-23 02:48

from django.db import migrations
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0061_product_thumbnail2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='thumbnail2',
        ),
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='products/'),
        ),
        migrations.AlterField(
            model_name='productgallery',
            name='galleryimg',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='products/product-gallery'),
        ),
        migrations.AlterField(
            model_name='review',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(null=True, upload_to='products/'),
        ),
    ]
