# Generated by Django 4.1.3 on 2022-11-23 21:18

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0064_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='attributes_type',
            field=models.CharField(blank=True, choices=[('COLOR', 'COLOR'), ('SIZE', 'SIZE'), ('OFFER', 'OFFER')], max_length=50, verbose_name='Одбери тип'),
        ),
        migrations.AlterField(
            model_name='product',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Содржина'),
        ),
    ]
