# Generated by Django 4.1.3 on 2022-11-23 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0065_alter_product_attributes_type_alter_product_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='session_id',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
