# Generated by Django 4.1.3 on 2022-11-23 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0067_alter_cart_product_alter_cart_product_qty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='session_id',
            field=models.CharField(max_length=1002),
        ),
    ]
