# Generated by Django 4.1.3 on 2022-11-23 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0071_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='product_qty',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='cartitems',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
    ]
