# Generated by Django 4.1.3 on 2022-11-23 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0073_cart_name_cart_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitems',
            options={'verbose_name': 'Cart Items', 'verbose_name_plural': 'Cart Items'},
        ),
    ]
