# Generated by Django 4.1.3 on 2022-11-23 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0074_alter_cartitems_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='user',
        ),
    ]
