# Generated by Django 4.1.3 on 2022-11-23 23:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0076_cartitems_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='session_id',
            new_name='session',
        ),
    ]
