# Generated by Django 4.1.3 on 2022-11-23 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0077_rename_session_id_cart_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='user',
            new_name='Cart',
        ),
    ]
