# Generated by Django 4.1.3 on 2022-11-23 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0078_rename_user_cartitems_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitems',
            old_name='Cart',
            new_name='cart',
        ),
    ]
