# Generated by Django 4.1.3 on 2022-11-24 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0081_orderfee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderfee',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.order'),
        ),
    ]
