# Generated by Django 4.1.3 on 2022-11-24 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0082_alter_orderfee_order'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderFee',
            new_name='OrderFees',
        ),
    ]
