# Generated by Django 4.1.3 on 2022-11-24 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0083_rename_orderfee_orderfees'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfees',
            name='order',
        ),
        migrations.AddField(
            model_name='orderfees',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
    ]
