# Generated by Django 4.1.3 on 2022-11-24 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0084_remove_orderfees_order_orderfees_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderfees',
            name='cart',
        ),
        migrations.CreateModel(
            name='CartFees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Име')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.cart')),
            ],
        ),
    ]
