# Generated by Django 4.1.3 on 2022-11-24 02:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0085_remove_orderfees_cart_cartfees'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartfees',
            name='fee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.orderfees'),
        ),
        migrations.AlterField(
            model_name='cartfees',
            name='cart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.cart'),
        ),
    ]
