# Generated by Django 4.1.3 on 2022-11-24 02:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0086_cartfees_fee_alter_cartfees_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderFees',
            new_name='CheckoutFees',
        ),
        migrations.CreateModel(
            name='OrderFeesItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Име')),
                ('price', models.IntegerField(verbose_name='Цена')),
                ('fee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.checkoutfees')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.order')),
            ],
        ),
    ]
