# Generated by Django 4.1.3 on 2022-11-24 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0088_product_shipping_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='shipping_price',
        ),
        migrations.AddField(
            model_name='order',
            name='shipping_price',
            field=models.IntegerField(blank=True, default=130),
        ),
    ]
