# Generated by Django 4.1.3 on 2022-11-24 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0089_remove_product_shipping_price_order_shipping_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartoffers',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
