# Generated by Django 4.1.3 on 2022-11-24 17:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0090_cartitems_is_added_cartoffers_is_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoffers',
            name='is_added',
        ),
    ]
