# Generated by Django 4.1.3 on 2022-11-24 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0091_remove_cartoffers_is_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderfeesitem',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
