# Generated by Django 4.1.3 on 2022-11-24 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0093_remove_orderfeesitem_is_added_checkoutfees_is_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoffers',
            name='is_added',
            field=models.BooleanField(default=False),
        ),
    ]
