# Generated by Django 4.1.3 on 2022-11-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0095_remove_cartitems_is_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartoffers',
            name='is_added',
            field=models.BooleanField(default=True),
        ),
    ]
