# Generated by Django 4.1.3 on 2022-11-24 18:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0101_remove_cartoffersadded_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartoffersadded',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.offer'),
        ),
    ]
