# Generated by Django 4.1.3 on 2022-11-24 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0102_cartoffersadded_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartoffersadded',
            name='offer',
        ),
    ]
