# Generated by Django 4.1.3 on 2022-11-24 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0104_alter_cartoffersadded_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartOffersAdded',
        ),
    ]
