# Generated by Django 4.1.3 on 2022-11-24 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0106_orderitem_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='price',
        ),
    ]
