# Generated by Django 4.1.3 on 2022-11-24 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0107_remove_offer_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productattribute',
            name='label',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
