# Generated by Django 4.1.3 on 2022-11-24 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0108_productattribute_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='attribute',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.productattribute'),
        ),
        migrations.AddField(
            model_name='cartitems',
            name='product_price',
            field=models.IntegerField(null=True),
        ),
    ]
