# Generated by Django 4.1.3 on 2022-11-24 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0110_remove_cartitems_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='attributename',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
