# Generated by Django 4.1.3 on 2022-11-24 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0111_cartitems_attributename'),
    ]

    operations = [
        migrations.AlterField(
            model_name='color',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
