# Generated by Django 4.1.3 on 2022-11-24 21:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0112_alter_color_title_alter_offer_title_alter_size_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='color',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.color'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='offer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.offer'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='size',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.size'),
            preserve_default=False,
        ),
    ]
