# Generated by Django 4.1.3 on 2022-11-24 21:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0113_alter_productattribute_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitems',
            name='attributename',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='offer',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.offer'),
            preserve_default=False,
        ),
    ]
