# Generated by Django 4.1.3 on 2022-11-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0115_alter_productattribute_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
