# Generated by Django 4.1.3 on 2022-11-24 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0116_alter_productattribute_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitems',
            name='attributeprice',
            field=models.IntegerField(null=True),
        ),
    ]
