# Generated by Django 4.1.3 on 2022-11-25 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0119_orderitem_supplier_alter_orderfeesitem_fee_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='color',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.color'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='offer',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.offer'),
        ),
        migrations.AlterField(
            model_name='productattribute',
            name='size',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.size'),
        ),
    ]
