# Generated by Django 4.1.3 on 2022-11-25 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0120_alter_productattribute_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='subtotal_price',
            field=models.IntegerField(default=1, verbose_name='Вкупна цена на продукти'),
            preserve_default=False,
        ),
    ]
