# Generated by Django 4.1.3 on 2022-11-25 02:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0122_alter_order_subtotal_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='price',
            field=models.IntegerField(verbose_name='Цена'),
        ),
    ]
