# Generated by Django 4.1.3 on 2022-11-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0123_alter_orderitem_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_from', models.CharField(max_length=100)),
                ('date_to', models.CharField(max_length=100)),
            ],
        ),
    ]
