# Generated by Django 4.1.3 on 2022-11-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0124_exportorder'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ExportOrder',
        ),
    ]
