# Generated by Django 4.1.3 on 2022-11-26 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0125_delete_exportorder'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date_test',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
