# Generated by Django 4.1.3 on 2022-11-27 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0126_order_date_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='order',
            name='date_test',
        ),
    ]
