# Generated by Django 4.1.3 on 2022-11-30 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0130_cartitems_offerprice_alter_cartoffers_is_added_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitems',
            name='offerprice',
        ),
        migrations.RemoveField(
            model_name='cartoffers',
            name='price',
        ),
    ]
